In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [5]:
class Net(nn.Module):
    
    def __init__(self):
        super(Net, self).__init__()
        self.conv1 = nn.Conv2d(1,6,3)
        self.conv2 = nn.Conv2d(6,16,3)
        self.fc1 = nn.Linear(16*6*6,120)
        self.fc2 = nn.Linear(120,84)
        self.fc3 = nn.Linear(84,10)
    
    def forword(self, x):
        x = F.max_pool2d(F.relu(self.conv1(x)),(2,2))
        x = F.max_pool2d(F.relu(self.conv2(x)),2)
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x
    
    def num_flat_features(self, x):
        size = x.size()[1:]
        num_features = 1
        for s in size:
            num_features *= s
            return num_features
        
        

In [6]:
net = Net()
print(Net)

<class '__main__.Net'>


In [8]:
list(net.parameters())

[Parameter containing:
 tensor([[[[-0.1324, -0.2625, -0.2936],
           [-0.0553, -0.0978,  0.1801],
           [-0.0728, -0.2630, -0.1562]]],
 
 
         [[[-0.2404,  0.0347, -0.0718],
           [ 0.0722,  0.3051, -0.0656],
           [-0.1625,  0.1411, -0.2788]]],
 
 
         [[[-0.0091, -0.1976, -0.2169],
           [-0.2359, -0.3121, -0.1085],
           [ 0.2706, -0.0589,  0.2532]]],
 
 
         [[[ 0.1715,  0.2857,  0.2527],
           [-0.2034,  0.2173, -0.2710],
           [ 0.2569,  0.1943,  0.0260]]],
 
 
         [[[-0.0348,  0.0332,  0.2127],
           [-0.1369,  0.2872, -0.3198],
           [ 0.0204, -0.0791,  0.2664]]],
 
 
         [[[-0.2337,  0.0067,  0.0865],
           [-0.0686, -0.1030, -0.1945],
           [ 0.2735, -0.2564, -0.0379]]]], requires_grad=True),
 Parameter containing:
 tensor([-0.2314,  0.2757, -0.2681, -0.0600, -0.3207, -0.3300],
        requires_grad=True),
 Parameter containing:
 tensor([[[[ 0.0608, -0.0223, -0.0589],
           [ 0.0812,  0.